// --- JWT & Auth ---
pub const DEFAULT_ISSUER: &str = "kelvin-root";
pub const DEFAULT_AUDIENCE: &str = "kelvin-memory-controller";
pub const MAX_REQUEST_ID_LENGTH: usize = 256;
pub const MAX_CLOCK_SKEW_SECS: u64 = 300;

// --- Timeouts & Limits ---
pub const DEFAULT_CLOCK_SKEW_SECS: u64 = 30;
pub const DEFAULT_TIMEOUT_MS: u64 = 2_000;
pub const DEFAULT_FUEL: u64 = 100_000;
pub const REPLAY_WINDOW_SECS: u64 = 120;
pub const MAX_REPLAY_WINDOW_SECS: u64 = 3_600;

// --- Memory & Module ---
pub const DEFAULT_MAX_MODULE_BYTES: usize = 2 * 1024 * 1024;
pub const DEFAULT_MAX_MEMORY_PAGES: u32 = 64;
pub const DEFAULT_MAX_RESPONSE_BYTES: usize = 1024 * 1024;

// --- Network ---
pub const DEFAULT_CONTROLLER_ADDR: &str = "127.0.0.1:50051";

// --- Memory Provider ---
pub const IN_MEMORY_PROVIDER_ID: &str = "in_memory";
pub const SEARCH_SNIPPET_CHAR_LIMIT: usize = 160;
pub const MIN_SEARCH_SCORE: f32 = 0.001;
pub const DEFAULT_SEARCH_START_LINE: u32 = 1;
pub const DEFAULT_SEARCH_END_LINE: u32 = 1;

// --- Environment Variables ---
pub const ENV_KELVIN_MEMORY_ISSUER: &str = "KELVIN_MEMORY_ISSUER";
pub const ENV_KELVIN_MEMORY_AUDIENCE: &str = "KELVIN_MEMORY_AUDIENCE";
pub const ENV_KELVIN_MEMORY_PUBLIC_KEY_PEM: &str = "KELVIN_MEMORY_PUBLIC_KEY_PEM";
pub const ENV_KELVIN_MEMORY_PUBLIC_KEY_PATH: &str = "KELVIN_MEMORY_PUBLIC_KEY_PATH";
pub const ENV_KELVIN_MEMORY_TLS_CERT_PEM: &str = "KELVIN_MEMORY_TLS_CERT_PEM";
pub const ENV_KELVIN_MEMORY_TLS_CERT_PATH: &str = "KELVIN_MEMORY_TLS_CERT_PATH";
pub const ENV_KELVIN_MEMORY_TLS_KEY_PEM: &str = "KELVIN_MEMORY_TLS_KEY_PEM";
pub const ENV_KELVIN_MEMORY_TLS_KEY_PATH: &str = "KELVIN_MEMORY_TLS_KEY_PATH";
pub const ENV_KELVIN_MEMORY_TLS_CLIENT_CA_PEM: &str = "KELVIN_MEMORY_TLS_CLIENT_CA_PEM";
pub const ENV_KELVIN_MEMORY_TLS_CLIENT_CA_PATH: &str = "KELVIN_MEMORY_TLS_CLIENT_CA_PATH";
pub const ENV_KELVIN_MEMORY_CLOCK_SKEW_SECS: &str = "KELVIN_MEMORY_CLOCK_SKEW_SECS";
pub const ENV_KELVIN_MEMORY_MAX_MODULE_BYTES: &str = "KELVIN_MEMORY_MAX_MODULE_BYTES";
pub const ENV_KELVIN_MEMORY_MAX_MEMORY_PAGES: &str = "KELVIN_MEMORY_MAX_MEMORY_PAGES";
pub const ENV_KELVIN_MEMORY_DEFAULT_FUEL: &str = "KELVIN_MEMORY_DEFAULT_FUEL";
pub const ENV_KELVIN_MEMORY_DEFAULT_TIMEOUT_MS: &str = "KELVIN_MEMORY_DEFAULT_TIMEOUT_MS";
pub const ENV_KELVIN_MEMORY_DEFAULT_MAX_RESPONSE_BYTES: &str =
    "KELVIN_MEMORY_DEFAULT_MAX_RESPONSE_BYTES";
pub const ENV_KELVIN_MEMORY_REPLAY_WINDOW_SECS: &str = "KELVIN_MEMORY_REPLAY_WINDOW_SECS";
pub const ENV_KELVIN_MEMORY_PROFILE: &str = "KELVIN_MEMORY_PROFILE";
pub const ENV_KELVIN_MEMORY_CONTROLLER_ADDR: &str = "KELVIN_MEMORY_CONTROLLER_ADDR";
pub const ENV_KELVIN_MEMORY_MODULE_MANIFEST: &str = "KELVIN_MEMORY_MODULE_MANIFEST";
pub const ENV_KELVIN_MEMORY_MODULE_WASM: &str = "KELVIN_MEMORY_MODULE_WASM";
pub const ENV_KELVIN_MEMORY_MODULE_WAT: &str = "KELVIN_MEMORY_MODULE_WAT";
pub const ENV_KELVIN_MEMORY_ALLOW_INSECURE_NON_LOOPBACK: &str =
    "KELVIN_MEMORY_ALLOW_INSECURE_NON_LOOPBACK";

// --- Module Runtime Error Codes ---
pub const MODULE_HOST_FN_NOT_FOUND: i32 = -1;
pub const MODULE_HOST_FN_OK: i32 = 0;
pub const MODULE_EXECUTION_SUCCESS: i32 = 0;

// --- Insecure Mode Flags ---
pub const INSECURE_MODE_FLAG_1: &str = "1";
pub const INSECURE_MODE_FLAG_TRUE: &str = "true";
pub const INSECURE_MODE_FLAG_YES: &str = "yes";
